server:
  port: 8083

spring:
  application:
    name: query-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
